name: Test and Generated APK

env:
  # The name of the main module repository
  main_project_module: composeApp


on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test
      # Create APK Debug
      - name: Build apk debug project (APK) module
        run: ./gradlew :composeApp:assembleDebug
      - name: Upload APK Debug - composeApp
        uses: actions/upload-artifact@v4
        with:
          name:  APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/
